name: store-ecosystem

networks:
  store-network:
    driver: bridge

volumes:
  pgdata:
  store_uploads:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

services:
  # Base de Dados da Loja
  postgres:
    image: postgres:16-alpine
    container_name: store-postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - store-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Qualidade de Código e Segurança Estática (SAST)
  sonarqube:
    image: sonarqube:lts-community
    container_name: store-sonarqube
    ports:
      - "9000:9000"
    networks:
      - store-network
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  # Backend Java/Spring Boot
  store-backend:
    build:
      context: ./Store
      dockerfile: Dockerfile.backend
    image: store-backend:latest
    container_name: store-backend
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: "8081"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - store_uploads:/app/uploads
    networks:
      - store-network

  # Gateway de Entrada
  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    image: store-gateway:latest
    container_name: store-gateway
    env_file:
      - ./.env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - store-backend
    ports:
      - "8080:8080"
    networks:
      store-network:
        aliases:
          - gateway

  # Frontend
  store-frontend:
    build:
      context: ./Store
      dockerfile: Dockerfile.frontend
    image: store-frontend:latest
    container_name: store-frontend
    depends_on:
      - gateway
    ports:
      - "8085:80"
    networks:
      - store-network

  # Túnel Cloudflare para Acesso Externo
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: store-tunnel
    env_file:
      - ./.env
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_URL=http://store-frontend:80
    networks:
      - store-network
    entrypoint:
      - cloudflared
      - tunnel
      - --url
      - http://store-frontend:80