server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 10M;

  location = / { return 301 /home; }

  # API -> Gateway
  location /api/ {

  # Preflight CORS
  if ($request_method = OPTIONS) {
    add_header Access-Control-Allow-Origin $http_origin always;
    add_header Vary Origin always;
    add_header Access-Control-Allow-Credentials "true" always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin, X-Requested-With" always;
    add_header Access-Control-Max-Age 86400 always;
    return 204;
  }

  add_header Access-Control-Allow-Origin $http_origin always;
  add_header Vary Origin always;
  add_header Access-Control-Allow-Credentials "true" always;
  add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
  add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin, X-Requested-With" always;

  proxy_pass http://store-gateway:8080;
  proxy_http_version 1.1;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_hide_header WWW-Authenticate;
}


  # MAGIC URLs
  location /home { try_files $uri $uri.html /home/index.html; }

  location /login { try_files $uri $uri.html /login/login.html =404; }
  location = /login/ { return 301 /login; }

  location /produtos { try_files $uri $uri.html /produtos/list.html =404; }
  location /upload { try_files $uri $uri.html /produtos/upload.html =404; }
  location = /upload/ { return 301 /upload; }

  location /cadastros { try_files $uri $uri.html /cadastros/register-seller.html =404; }

  location /resetpassword { try_files $uri $uri.html /resetpassword/forgot-password.html =404; }

  location / { try_files $uri $uri/ /home/index.html; }

  location /images/ {
    alias /usr/share/nginx/html/images/;
    try_files $uri /images/placeholder.jpg;
  }

  location /uploads/ {
    alias /usr/share/nginx/html/uploads/;
    try_files $uri /images/placeholder.jpg;
  }
}
